#!/bin/bash
# Thomas Arend
# 03.10.2016

# Erstellen eines Freifunk Image unter Debian

DIALOG='kdialog --title Make-FF-Images'

GLUONGIT="https://github.com/freifunk-gluon/gluon.git"
GLUONDIR=`$DIALOG --inputbox GLUONDIR "$HOME/gluon"`
GLUONVER=`$DIALOG --inputbox GLUONVER "master"`

SITEGIT="https://github.com/Byggvir/ff-rhb.git"
SITEVER=${GLUONVER}

BRANCH=`$DIALOG --inputbox BRANCH ${SITEVER}`

GLUON_RELEASE=`$DIALOG --inputbox GLUON_RELEASE "v2017.1.4-$(date '+%Y%m%d')-${BRANCH}"`

if [ $BRANCH != "master" ] 
then 
  $DIALOG --yesno "USB-Support" && USB="YES" && BRANCH="${BRANCH}usb" && SITEVER="${SITEVER}-usb"
  GLUON_RELEASE="${GLUON_RELEASE}-usb"
else
  USB="YES"
fi


TARGETS="ar71xx-generic ar71xx-tiny ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709 mpc85xx-generic x86-64 x86-generic" 
#TARGETS="ar71xx-generic ar71xx-tiny ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709 mpc85xx-generic x86-generic x86-geode x86-64 ramips-mt7620 ramips-mt7621 ramips-mt7628 ramips-rt305x" 
#TARGETS="ar71xx-generic" 

echo "VERSION (gluon): $GLUONVER"
echo "VERSION (site): $SITEVER"
echo "BRANCH: $BRANCH"

function mktarget () {

  make V=s clean GLUON_TARGET="$1" GLUON_RELEASE="$GLUON_RELEASE" >$HOME/__tmp/${SITEVER}-mkffimage-$1-a.log 2>&1
  make V=s GLUON_TARGET="$1" GLUON_RELEASE="$GLUON_RELEASE" >/tmp/${SITEVER}-mkffimage-$1-b.log 2>&1

}

if [ ! -d "${GLUONDIR}/${SITEVER}" ]
then
### Verzeichnis existiert noch nicht ###
  pushd "${GLUONDIR}"
  git clone -b ${GLUONVER} ${GLUONGIT} ${SITEVER} 
  popd
else 
### Verzeichnis vorhanden, auffrischen ###
  if [ "$USB" = "YES" ]
  then
    rm "${GLUONDIR}/${SITEVER}/package/gluon-wan-dnsmasq/files/etc/hotplug.d/iface/50-gluon-wan-dnsmasq" 
    rm "${GLUONDIR}/${SITEVER}/package/gluon-wan-dnsmasq/luasrc/lib/gluon/wan-dnsmasq/update.lua"
  fi
  pushd "${GLUONDIR}/${SITEVER}"
  git pull "${GLUONGIT}"
  ## make dirclean
  popd
fi

## USB Patch
## Zusätzliche Schnittstellen tether und umts einrichten

if [ "$USB" = "YES" ]
then
  patch "${GLUONDIR}/${SITEVER}/package/gluon-wan-dnsmasq/files/etc/hotplug.d/iface/50-gluon-wan-dnsmasq"  "${GLUONDIR}/patches/50-gluon-wan-dnsmasq.patch"
  patch "${GLUONDIR}/${SITEVER}/package/gluon-wan-dnsmasq/luasrc/lib/gluon/wan-dnsmasq/update.lua" "${GLUONDIR}/patches/update.lua.patch"
fi

### Wir brauchen noch die Site Infos ###

pushd "${GLUONDIR}/${SITEVER}"

if [ ! -d site ]
then 
  git clone -b "${SITEVER}" "${SITEGIT}" site 
else
  pushd site
  git pull "${SITEGIT}" ${SITEVER}
  popd
fi


#pushd package
#if [ ! -d gluon-status-page-rheinbach ]
#then 
#  git clone https://github.com/Byggvir/gluon-status-page-rheinbach.git gluon-status-page-rheinbach 
#else
#  pushd gluon-status-page-rheinbach
#    git pull https://github.com/Byggvir/gluon-status-page-rheinbach.git
#  popd
#fi
#popd


### Alte Log-Dateien löschen ###

rm $HOME/__tmp/${SITEVER}-mkffimage*.log

### Alles bereit um die Firmware zu erstellen ###

make update >$HOME/__tmp/${SITEVER}-mkffimage.log 2>&1

for TARGET in ${TARGETS}
do
  mktarget ${TARGET}
done

make manifest GLUON_BRANCH=${BRANCH} GLUON_RELEASE="$GLUON_RELEASE" GLUON_PRIORITY=1
./contrib/sign.sh $HOME/.ecdsa/thomas.secret output/images/sysupgrade/${BRANCH}.manifest

popd
