#!/bin/sh
# Thomas Arend
# 03.10.2016

GLUONDIR=$HOME/gluon
BRANNCH=stable

if [ -z "$1" ]
then
  GLUONVER=v2016.2
else
  GLUONVER=$1 
fi

if [ -z "$2" ]
then
  SITEVER=${GLUONVER}
else
  SITEVER=${GLUONVER}-$2 
  BRANCH=${BRANCH}-$2
fi

function mktarget () {

  make V=s clean GLUON_TARGET=$1 >$HOME/__tmp/${SITEVER}-mkffimage-$1-a.log 2>&1
  make V=s GLUON_TARGET=$1 >$HOME/__tmp/${SITEVER}-mkffimage-$1-b.log 2>&1

}

if [ ! -d "${GLUONDIR}/${SITEVER}" ]
then
### Verzeichnis existiert noch nicht ###
  pushd "${GLUONDIR}"
  git clone -b ${GLUONVER} https://github.com/freifunk-gluon/gluon.git ${SITEVER} 
  popd
else 
### Verzeichnis vorhanden, auffrischen ###  
  pushd "${GLUONDIR}/${SITEVER}"
  git pull https://github.com/freifunk-gluon/gluon.git
  ## make dirclean
  popd
fi

### Wir brauchen noch die Site Infos ###

pushd "${GLUONDIR}/${SITEVER}"

if [ ! -d site ]
then 
  git clone -b ${SITEVER} https://github.com/Byggvir/ff-rhb.git site 
else
  pushd site
  git pull https://github.com/Byggvir/ff-rhb.git ${SITEVER}
  popd
fi

#pushd package
#if [ ! -d gluon-status-page-rheinbach ]
#then 
#  git clone https://github.com/Byggvir/gluon-status-page-rheinbach.git gluon-status-page-rheinbach 
#else
#  pushd gluon-status-page-rheinbach
#    git pull https://github.com/Byggvir/gluon-status-page-rheinbach.git
#  popd
#fi
#popd
### Alles bereit um die Firmware zu erstellen ###

rm $HOME/__tmp/${SITEVER}-mkffimage*.log

make update >$HOME/__tmp/${SITEVER}-mkffimage.log 2>&1

## Die folgenden Targets ar71xx-nand mpc85xx-generic x86-generic x86-kvm_guest betreffen nur 7 Router.
## Daher kann ggf. auf die Erstellung dieser Images verzichtet werden.

for TARGET in \
  ar71xx-generic \
  ar71xx-nand \
  brcm2708-bcm2708 \
  brcm2708-bcm2709 \
  mpc85xx-generic \
  x86-64 \
  x86-generic \
  x86-kvm_guest \
  x86-xen_domu \
  
#  ramips-mt7621 \
#  ramips-rt305x \
#  sunxi 
do
  mktarget ${TARGET}
done

make manifest GLUON_BRANCH=${BRANCH} GLUON_PRIORITY=1
./contrib/sign.sh $HOME/.ecdsa/thomas.secret output/images/sysupgrade/${BRANCH}.manifest

popd
