#!/bin/sh
# Thomas Arend
# 03.01.2016

GLUONDIR=gluon
GLUONVER=v2015.1.x
if [ ! -d "$GLUONDIR/$GLUONVER" ]
then
### Verzeichnis existiert noch nicht ###
  mkdir -p "$GLUONDIR/$GLUONVER"
  pushd "$GLUONDIR/$GLUONVER"
  git clone https://github.com/freifunk-gluon/gluon.git -b v2015.1.x
  popd
else 
### Verzeichnis vorhanden, auffrischen ###  
  pushd "$GLUONDIR/$GLUONVER/gluon"
  git pull https://github.com/freifunk-gluon/gluon.git v2015.1.x
  make dirclean
  popd
fi

### Wir brauchen noch die Site Infos ###
pushd "$GLUONDIR/$GLUONVER/gluon"

if [ ! -d site ]
then 
  git clone https://github.com/Byggvir/ff-rhb.git site 
else
  pushd site
  git pull https://github.com/Byggvir/ff-rhb.git master
  popd
fi

### Alles bereit um die Firmware zu ersetllen ###

make update
make clean GLUON_TARGET=ar71xx-generic
make GLUON_TARGET=ar71xx-generic

## Die folgenden Targets betreffen nur wenige 7 Router.
## Daher wird auf die Erstellung dieser Images verzichtet.

# make clean GLUON_TARGET=ar71xx-nand
# make GLUON_TARGET=ar71xx-nand
# make clean GLUON_TARGET=mpc85xx-generic
# make GLUON_TARGET=mpc85xx-generic
# make clean GLUON_TARGET=x86-generic
# make GLUON_TARGET=x86-generic
# make clean GLUON_TARGET=x86-kvm_guest
# make GLUON_TARGET=x86-kvm_guest

popd
