#!/bin/sh
# Thomas Arend
# 03.01.2016

GLUONDIR=gluon
GLUONVER=v2015.1.x
if [ ! -d "$GLUONDIR/$GLUONVER" ]
then
  pushd "$GLUONDIR"
  git clone https://github.com/freifunk-gluon/gluon.git -b v2015.1.x
  popd
else 
  pushd "$GLUONDIR/$GLUONVER"
  git pull https://github.com/freifunk-gluon/gluon.git v2015.1.x
  popd
fi
pushd "$GLUONDIR/$GLUONVER"

make dirclean
make update
make clean GLUON_TARGET=ar71xx-generic
make -j5 GLUON_TARGET=ar71xx-generic
make clean GLUON_TARGET=ar71xx-nand
make -j5 GLUON_TARGET=ar71xx-nand
make clean GLUON_TARGET=mpc85xx-generic
make -j5 GLUON_TARGET=mpc85xx-generic
make clean GLUON_TARGET=x86-generic
make -j5 GLUON_TARGET=x86-generic
make clean GLUON_TARGET=x86-kvm_guest
make -j5 GLUON_TARGET=x86-kvm_guest

popd
